//Action type object dictionary, which defined all the ations for dispatch

//Category action type
export const categoryType = {
  CATEGORY_ALL_GET: 'CATEGORY_ALL_GET',
  CATEGORY_ALL_SUCCEEDED: 'CATEGORY_ALL_SUCCEEDED',
  CATEGORY_ALL_FAILED: 'CATEGORY_ALL_FAILED',
  CATEGORY_SAVE: 'CATEGORY_SAVE',
  CATEGORY_SAVE_SUCCEEDED: 'CATEGORY_SAVE_SUCCEEDED',
  CATEGORY_SAVE_FAILED: 'CATEGORY_SAVE_FAILED'
}

//Album action type
export const albumType = {
  ALBUM_GET: 'ALBUM_GET',
  ALBUM_GET_SUCCEEDED: 'ALBUM_GET_SUCCEEDED',
  ALBUM_GET_FAILED: 'ALBUM_GET_FAILED',
  ALBUM_SAVE: 'ALBUM_SAVE',
  ALBUM_SAVE_SUCCEEDED: 'ALBUM_SAVE_SUCCEEDED',
  ALBUM_SAVE_FAILED: 'ALBUM_SAVE_FAILED',
  ALBUM_DELETE: 'ALBUM_DELETE',
  ALBUM_DELETE_SUCCEEDED: 'ALBUM_DELETE_SUCCEEDED',
  ALBUM_DELETE_FAILED: 'ALBUM_DELETE_FAILED',
  ALBUM_UPDATE: 'ALBUM_UPDATE',
  ALBUM_UPDATE_SUCCEEDED: 'ALBUM_UPDATE_SUCCEEDED',
  ALBUM_UPDATE_FAILED: 'ALBUM_UPDATE_FAILED',
  ALBUM_INITIAL_STATE: 'ALBUM_INITIAL_STATE',
  ALBUM_SUCCEES_STATE: 'ALBUM_SUCCEES_STATE',
  ALBUM_FAILE_STATE: 'ALBUM_FAILE_STATE'  
}

//Photo action type
export const photoType = {
  PHOTO_GET: 'PHOTO_GET',
  PHOTO_GET_SUCCEEDED: 'PHOTO_GET_SUCCEEDED',
  PHOTO_GET_FAILED: 'PHOTO_GET_FAILED',
  PHOTO_SAVE: 'PHOTO_SAVE',
  PHOTO_SAVE_SUCCEEDED: 'PHOTO_SAVE_SUCCEEDED',
  PHOTO_SAVE_FAILED: 'PHOTO_SAVE_FAILED',
  PHOTO_DELETE: 'PHOTO_DELETE',
  PHOTO_DELETE_SUCCEEDED: 'PHOTO_DELETE_SUCCEEDED',
  PHOTO_DELETE_FAILED: 'PHOTO_DELETE_FAILED',
  PHOTO_UPDATE: 'PHOTO_UPDATE',
  PHOTO_UPDATE_SUCCEEDED: 'PHOTO_UPDATE_SUCCEEDED',
  PHOTO_UPDATE_FAILED: 'PHOTO_UPDATE_FAILED',  
  PHOTO_VIEW: 'PHOTO_VIEW',
  PHOTO_INITIAL_STATE: 'PHOTO_INITIAL_STATE',
  PHOTO_SUCCEES_STATE: 'PHOTO_SUCCEES_STATE',
  PHOTO_FAILE_STATE: 'PHOTO_FAILE_STATE'
}

export const tabType = {
  TAB_KEY: 'TAB_KEY'
}