//Action type object dictionary, which defined all the ations for dispatch

//Category action type
export const categoryType = {
  CATEGORY_ALL_GET: 'CATEGORY_ALL_GET',
  CATEGORY_ALL_SUCCEEDED: 'CATEGORY_ALL_SUCCEEDED',
  CATEGORY_ALL_FAILED: 'CATEGORY_ALL_FAILED',
  CATEGORY_SAVE: 'CATEGORY_SAVE',
  CATEGORY_SAVE_SUCCEEDED: 'CATEGORY_SAVE_SUCCEEDED',
  CATEGORY_SAVE_FAILED: 'CATEGORY_SAVE_FAILED'
}

//Album action type
export const albumType = {
  ALBUM_GET: 'ALBUM_GET',
  ALBUM_GET_SUCCEEDED: 'ALBUM_GET_SUCCEEDED',
  ALBUM_GET_FAILED: 'ALBUM_GET_FAILED',
  ALBUM_SAVE: 'ALBUM_SAVE',
  ALBUM_SAVE_SUCCEEDED: 'ALBUM_SAVE_SUCCEEDED',
  ALBUM_SAVE_FAILED: 'ALBUM_SAVE_FAILED',
  ALBUM_DELETE: 'ALBUM_DELETE',
  ALBUM_DELETE_SUCCEEDED: 'ALBUM_DELETE_SUCCEEDED',
  ALBUM_DELETE_FAILED: 'ALBUM_DELETE_FAILED'
}

//Picture action type
export const pictureType = {
  PICTURE_GET: 'PICTURE_GET',
  PICTURE_GET_SUCCEEDED: 'PICTURE_GET_SUCCEEDED',
  PICTURE_GET_FAILED: 'PICTURE_GET_FAILED',
  PICTURE_SAVE: 'PICTURE_SAVE',
  PICTURE_SAVE_SUCCEEDED: 'PICTURE_SAVE_SUCCEEDED',
  PICTURE_SAVE_FAILED: 'PICTURE_SAVE_FAILED',
  PICTURE_VIEW: 'PICTURE_VIEW'
}

